### PR TITLE
Fix issue with creating and finding sync resources

### PR DESCRIPTION
**Pull request by ryanwjackson**
@mattgmarcus I believe this should fix your issue.

### CODE REVIEW

**Comment by ryanwjackson** [comment]
@mattgmarcus Did you test this?  If so, mind approving and merging?

**Review by mattgmarcus — APPROVED** [review]
Forgot to approve earlier. It worked :)

**Comment by mattgmarcus** [comment]
I'm getting this message about this being a protected branch and that I'm not authorized to review. Is this a new github feature?
https://help.github.com/en/articles/about-protected-branches

**Comment by ryanwjackson** [comment]
Added you as an admin.


--
Ryan Jackson
ryanwjackson@gmail.com

**Pull request merged**
